# Generated by Django 6.1 on 2026-09-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mahinay_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('check_in_date', models.CharField(max_length=100)),
                ('check_out_date', models.CharField(max_length=100)),
                ('reservation_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
