# Generated by Django 6.1 on 2026-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mahinay_App', '0002_hotel_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('check_in_date', models.CharField(max_length=100)),
                ('check_out_date', models.CharField(max_length=100)),
                ('number_of_guests', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
