# Generated by Django 6.1.1 on 2026-10-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mahinay_App', '0003_reservation_delete_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
